// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DnsChildRelationship
    {
        /// <summary>
        /// Initializes a new instance of the DnsChildRelationship class.
        /// </summary>
        public DnsChildRelationship()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DnsChildRelationship class.
        /// </summary>
        public DnsChildRelationship(string childDomain = default(string), string parentDomain = default(string), string type = default(string))
        {
            ChildDomain = childDomain;
            ParentDomain = parentDomain;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "childDomain")]
        public string ChildDomain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentDomain")]
        public string ParentDomain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; private set; }

    }
}
