// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DnsPtrRelationship
    {
        /// <summary>
        /// Initializes a new instance of the DnsPtrRelationship class.
        /// </summary>
        public DnsPtrRelationship()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DnsPtrRelationship class.
        /// </summary>
        public DnsPtrRelationship(string ipAddress = default(string), string domain = default(string), string type = default(string))
        {
            IpAddress = ipAddress;
            Domain = domain;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ipAddress")]
        public string IpAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "domain")]
        public string Domain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; private set; }

    }
}
