// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class INodeRelationship
    {
        /// <summary>
        /// Initializes a new instance of the INodeRelationship class.
        /// </summary>
        public INodeRelationship()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the INodeRelationship class.
        /// </summary>
        public INodeRelationship(string type = default(string))
        {
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; private set; }

    }
}
