version: '3'

services:
  graphdb.api:
    image: graphdb.api
    build:
      context: ./GraphDb.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - graphdb.neo4j
    environment:
      - Neo4jUri=bolt://graphdb.neo4j:7687

  graphdb.neo4j:
    image: "neo4j:3.2"
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none